- hosts: ubuntu
  tasks:
  - name: Install debian apache
    apt:
      name: apache2
      state: present

  - name: Start debian apache
    systemd:
      name: apache2
      enabled: yes

  - name: Install unzip
    apt:
      name: unzip
      state: present

  - name: unuarchive file that needs to be downloaded
    unarchive:
      src:  https://www.free-css.com/assets/files/free-css-templates/download/page283/ninom.zip
      dest: /tmp
      remote_src: yes
    
  - name: Copy content of tmp
    copy:
      src: /tmp/ninom-html/
      dest: /var/www/html/
      remote_src: yes 
      